//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _342Petryaeva_FINDTICKETS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int id { get; set; }
        public Nullable<int> ID_Departure_Airoport { get; set; }
        public Nullable<int> ID_Arrival_Airoport { get; set; }
        public Nullable<int> num_of_seats { get; set; }
        public Nullable<System.DateTime> time_departure { get; set; }
        public Nullable<int> ID_TicketType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Ticket_Type Ticket_Type { get; set; }
    }
}
